POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "player2@gmail.com",
    "password": "player2"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "player2@gmail.com",
    "password": "player2"
}
###

POST http://localhost:3000/lobby/create-lobby
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.Ng.wzDO5FU7Xvwv64WJSLOtrX3JO1jlf4H3PSFNt78pQFQ
Content-Type: application/json

{
    "lobbyName": "foot"
}

###

POST http://localhost:3000/lobby/add-member
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.Ng.wzDO5FU7Xvwv64WJSLOtrX3JO1jlf4H3PSFNt78pQFQ
Content-Type: application/json

{
    "memberId": "6",
    "lobbyId": "1"
}

###

POST http://localhost:3000/lobby/sendMessage
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.Mg.5O2kRS3jzuT6KYOimJSt9APJEvr4ZvV2W_mjkYM8ZWk
Content-Type: application/json

{
    "message": "test7"
}

###

GET http://localhost:3000/lobby/get-message?page=1&limit=2
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.Mg.5O2kRS3jzuT6KYOimJSt9APJEvr4ZvV2W_mjkYM8ZWk

