POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "player2@gmail.com",
    "password": "player2"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "player3@gmail.com",
    "password": "player3"
}
###

POST http://localhost:3000/lobby/create-lobby
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.Ng.wzDO5FU7Xvwv64WJSLOtrX3JO1jlf4H3PSFNt78pQFQ
Content-Type: application/json

{
    "lobbyName": "foot"
}

###

POST http://localhost:3000/lobby/add-member
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.Ng.wzDO5FU7Xvwv64WJSLOtrX3JO1jlf4H3PSFNt78pQFQ
Content-Type: application/json

{
    "memberId": "6",
    "lobbyId": "1"
}

###

POST http://localhost:3000/lobby/sendMessage
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.Mw.DskTki35U_FXh-7hcUot3Ktb5ZNNrzn_37P14nqe6MY
Content-Type: application/json

{
    "message": "ts"
}